/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/RoutingView3D.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Anteena_Bands.geometry}
          material={materials.Anteena_Bands}
          position={[0, -0.105, -0.774]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Back.geometry}
          material={materials.Back}
          position={[0, -0.406, 2.251]}
        />
        <group position={[0.188, -0.156, 2.251]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh007.geometry}
            material={materials.Logo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh007_1.geometry}
            material={materials.Back_Glass}
          />
        </group>
        <group position={[0, -0.136, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002.geometry}
            material={materials.Plastic_Glossy_Low}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_1.geometry}
            material={materials.Plastic_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_2.geometry}
            material={materials.Frame}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_3.geometry}
            material={materials["Frame.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_4.geometry}
            material={materials.Silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_5.geometry}
            material={materials.Gold}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bolts.geometry}
          material={materials.Silver}
          position={[0, 0, -0.004]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Buttons.geometry}
          material={materials["Frame.001"]}
          position={[0, 0, -0.594]}
        />
        <group position={[1.555, -0.733, -5.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials.Plastic_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials.Plastic_Glossy_Low}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Camera_Rings.geometry}
          material={materials["Frame.001"]}
          position={[1.555, -0.772, -5.76]}
        />
        <group position={[0, 0.348, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001.geometry}
            material={materials.Display}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_1.geometry}
            material={materials.Plastic_Glossy_Low}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_2.geometry}
            material={materials.Plastic_Rough}
          />
        </group>
        <group position={[0, 0.413, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials.Plastic_Glossy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_2.geometry}
            material={materials.Glass_Clear}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lens.geometry}
          material={materials.Lens}
          position={[1.493, -0.239, -5.992]}
        />
        <group position={[0.121, -0.767, -5.759]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh011.geometry}
            material={materials.Plastic_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh011_1.geometry}
            material={materials.Glass_Clear}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials.Plastic_Rough}
          position={[0, 0, 8.022]}
        />
        <group position={[0, 0, 7.775]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh013.geometry}
            material={materials.Plastic_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh013_1.geometry}
            material={materials.Gold}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/RoutingView3D.glb");
